spring:
  h2.console:
    enabled: true
    path: '/console'
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:h2:file:./AppDB'
  jpa:
    hibernate:
      ddl-auto: validate
task.allowMultipleTaskFromTemplate: false
